### ISSUE TITLE
make出错，lib/CMakeFiles/uhd.dir/usrp/OpenUSRP/limesdr_impl.cpp.o

### ISSUE THREAD

**Issue by BG7YWL** [jocover/OpenUSRP#10]
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp:1148:52: error: ‘class lime::IConnection’ has no member named ‘GetHardwareTimestampRate’
   _conn->SetHardwareTimestamp(time.to_ticks(_conn->GetHardwareTimestampRate()));
                                                    ^
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp: In member function ‘uhd::time_spec_t limesdr_impl::getHardwareTime(const string&)’:
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp:1161:46: error: ‘class lime::IConnection’ has no member named ‘GetHardwareTimestamp’
   time = uhd::time_spec_t::from_ticks(_conn->GetHardwareTimestamp(), _conn->GetHardwareTimestampRate());
                                              ^
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp:1161:77: error: ‘class lime::IConnection’ has no member named ‘GetHardwareTimestampRate’
   time = uhd::time_spec_t::from_ticks(_conn->GetHardwareTimestamp(), _conn->GetHardwareTimestampRate());
                                                                             ^
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp: At global scope:
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp:1209:29: warning: unused parameter ‘dir’ [-Wunused-parameter]
 uhd::filter_info_base::sptr limesdr_impl::getFilter(const uhd::direction_t dir, const size_t channel, const std::string &name) {
                             ^
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp:1209:29: warning: unused parameter ‘channel’ [-Wunused-parameter]
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp:1209:29: warning: unused parameter ‘name’ [-Wunused-parameter]
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp:1214:6: warning: unused parameter ‘dir’ [-Wunused-parameter]
 void limesdr_impl::setFilter(const uhd::direction_t dir, const size_t channel, const std::string &name, const filter_info_base::sptr filter) {
      ^
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp:1214:6: warning: unused parameter ‘channel’ [-Wunused-parameter]
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp:1214:6: warning: unused parameter ‘name’ [-Wunused-parameter]
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp:1214:6: warning: unused parameter ‘filter’ [-Wunused-parameter]
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp:1218:6: warning: unused parameter ‘enable’ [-Wunused-parameter]
 void limesdr_impl::setAutoTickRate(const bool enable) {
      ^
make[2]: *** [lib/CMakeFiles/uhd.dir/usrp/OpenUSRP/limesdr_impl.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp: In member function ‘virtual size_t LimeRxStream::get_max_num_samps() const’:
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp:103:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp: In member function ‘virtual size_t LimeTxStream::get_max_num_samps() const’:
/home/kk/uhd/host/lib/usrp/OpenUSRP/limesdr_io_impl.cpp:298:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
make[2]: *** [lib/CMakeFiles/uhd.dir/usrp/OpenUSRP/limesdr_io_impl.cpp.o] 错误 1
make[1]: *** [lib/CMakeFiles/uhd.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by FFY00** [comment]
The lime driver structure has changed. You should use SoapySDR (w/ SoapyLMS7 and SoapyUHD plugins) instead.

**Comment by shinan6** [comment]
What do you mean by using SoapySDR? Does it contain the desired LimeSDR driver we need? Should we install SoapySDR instead of LimeSuite now to get the proper driver?

**Comment by FFY00** [comment]
@Summity no, SoapySDR is just a platform. LimeSuite has the SoapyLMS7 plugin for SoapySDR. You should install both.

You can achieve what you want (use LimeSDR with the UHD driver) using SoapySDR with the plugings for LimeSDR and UHD. Those being SoapyLMS7 (included in LimeSuite) and SoapyUHD, respectively.
It works like this.
```
HARDWARE |                                SOFTWARE
LimeSDR <-> LimeSuite <-> SoapyLMS7 <-> SoapySDR <->  SoapyUHD <-> UHD <-> Software using UHD
```
Please note that SoapyLM7 and SoapyUHD are just plugins that act as an interface between the two drivers.

You should install the software from git according to this order:
  * Install [SoapySDR](https://github.com/pothosware/SoapySDR)
  * Install [LimeSuite](https://github.com/myriadrf/LimeSuite) (which includes [SoapyLMS7](https://github.com/myriadrf/LimeSuite/tree/master/SoapyLMS7))
  * Install [UHD](https://github.com/EttusResearch/uhd)
  * Install [SoapyUHD](https://github.com/pothosware/SoapyUHD)

I highly recommend you to read the [SoapySDR wiki](https://github.com/pothosware/SoapySDR/wiki)!

**Comment by Red-Owl** [comment]
const size_t numRFICs = devInfo.addrsLMS7002M.size(); is removed, is possible to replace ?
please read https://github.com/myriadrf/LimeSuite/search?utf8=%E2%9C%93&q=addrsLMS7002M&type=
tnx
