### ISSUE TITLE
make issue "lime::DeviceInfo’ has no member named ‘addrsLMS7002M’"

### ISSUE THREAD

**Issue by sovi123** [jocover/OpenUSRP#9]
OpenUSRP/limesdr_impl.cpp:127:34: error: ‘const struct lime::DeviceInfo’ has no member named ‘addrsLMS7002M’

**Comment by j0rGeT** [comment]
same problem, how to resolve?

**Comment by FFY00** [comment]
This was already addressed in #10 . Please have a look.
